CREATE DATABASE IF NOT EXISTS flowboard_auth;
CREATE DATABASE IF NOT EXISTS flowboard_workspace;
CREATE DATABASE IF NOT EXISTS flowboard_board;
CREATE DATABASE IF NOT EXISTS flowboard_list;
CREATE DATABASE IF NOT EXISTS flowboard_card;
CREATE DATABASE IF NOT EXISTS flowboard_notification;
CREATE DATABASE IF NOT EXISTS flowboard_comment;
CREATE DATABASE IF NOT EXISTS flowboard_payment;

-- If DB_USERNAME is not root, also add:
CREATE USER IF NOT EXISTS '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO '${DB_USERNAME}'@'%';
FLUSH PRIVILEGES;